# Create github action on develop branch 

name: Github Actions Demo
on: 
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🎉 The job was automatically triggered by a ${{ github.branch_name }} branch."    
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

